#
# prototype wind power generated by a windfarm
#
# Weibull wind distribution
#
#
source("normd.R")

power_curve <- function(w) {
  #
  # power (MW) from wind speed (w) in m/sec
  # Vestas V112 3MW turbine
  #
  pc <- 3.5/((11-3)^3)
  
  if (w < 3) { p <- 0 }
  if ((w >= 3) && (w < 11)) { p <- pc*(w-3)^3 }
  if ((w >= 11) && (w < 25)) { p <- 3.5 }
  if (w >= 25) { p <- 0 }
  
  p
}

wind <- rweibull(1000,3.5)

# mean of 6.6m/sec

wind <- wind*6.6 

power <- lapply(wind,power_curve)

# to size wind as equal to solar at 14:00pm

farm_power <- unlist(power)*(2.44/0.4)

wind_density <- density(farm_power,from=0,to=10.0)

wind_density$x[which(wind_density$x<0)] <- 0

wind_density <- normd(wind_density)


plot(wind_density)

# print(mean(wind_density))
# print(sum_probs(wind_density))

save(wind_density,file="../rdata/wind_density.rd")

